import "@/app/globals.css";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { Header } from "@/components/layout/header";

const notoSansJP = Noto_Sans_JP({
  preload: true,
  subsets: ['latin'],
  weight: ['400', '500', '700'], // 必要なウェイトのみ指定
  display: 'swap',
  variable: '--font-noto-sans-jp',
});

export const metadata: Metadata = {
  title: 'Kakeibo Design｜身近なお金の管理をサポート',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} min-h-screen antialiased`}
      >
        <Header showBreadcrumbs={true} />
        <main className="container mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
